<template>
  <div class="manage-layout performance-page">
    <div class="page-header"><div><h1 class="page-title">ประเมินผลงานรอบปี</h1><p class="page-subtitle">สรุปผลการปฏิบัติหน้าที่รายบุคคล</p></div><button class="btn-primary" :disabled="!person || exporting" @click="exportWord">📄 ดาวน์โหลด Word</button></div>
    <section class="card filter-card"><div class="filter-controls"><div class="filter-group"><label>รอบปีประเมิน</label><select v-model="year"><option v-for="y in years" :key="y" :value="y">{{ yearLabel(y) }}</option></select></div><div class="filter-group"><label>บุคคล</label><select v-model="person"><option value="">เลือกบุคคล</option><option v-for="p in filters.people" :key="p.id" :value="String(p.id)">{{ p.full_name }}{{ p.position_name ? ` (${p.position_name})` : '' }}</option></select></div></div></section>
    <section v-if="loading" class="card empty-state">กำลังโหลดข้อมูล...</section>
    <section v-else-if="!person" class="card empty-state">กรุณาเลือกรอบปีและบุคคลเพื่อแสดงข้อมูล</section>
    <section v-else-if="record" class="card report-card"><div class="report-heading"><h2>สรุปผลการปฏิบัติหน้าที่</h2><span>{{ yearLabel(year) }}</span></div><table class="data-table"><tbody><tr><th>ชื่อ-สกุล</th><td>{{ record.full_name }}</td><th>อาชีพ</th><td>{{ record.occupation || '-' }}</td></tr><tr><th>จำนวนเวรที่ปฏิบัติ</th><td>{{ record.duty_days }} วัน</td><th>ปฏิบัติหน้าที่อื่น/เข้าร่วมกิจกรรม</th><td>{{ record.activity_count }} ครั้ง</td></tr><tr><th>จำนวนการแลกเปลี่ยนเวร (ผู้ขอเปลี่ยนเวร)</th><td>{{ record.swap_count }} ครั้ง</td><th>การลาในแบบฟอร์ม</th><td>{{ leaveSummary(record) }}</td></tr></tbody></table></section>
  </div>
</template>
<script setup>
import { ref, computed, onMounted, watch } from 'vue'; import api from '../services/api'; import { swalError } from '../utils/swal'
const now = new Date(); const year = ref(String(now.getMonth() < 3 ? now.getFullYear()-1 : now.getFullYear())); const person = ref(''); const filters = ref({ people: [] }); const record = ref(null); const loading = ref(false); const exporting = ref(false); const years = computed(() => [Number(year.value), Number(year.value)-1, Number(year.value)-2])
const yearLabel = value => { const buddhist = Number(value) + 543; return `รอบปี ${buddhist} (1 เม.ย. ${String(buddhist).slice(-2)} - 31 มี.ค. ${String(buddhist + 1).slice(-2)})` }
const leaveSummary = row => { const leaves = row?.leaves || {}; const personal = ['ลากิจส่วนตัว', 'ลากิจ', 'ลาพักผ่อน'].reduce((sum, key) => sum + Number(leaves[key]?.days || 0), 0); return `ลากิจ/ลาพักผ่อน ${personal || '-'} วัน · ลาป่วย ${leaves['ลาป่วย']?.count || '-'} ครั้ง · ขาด - วัน (ไม่ลา)` }
const load = async () => { loading.value = true; try { const r = await api.get('/performance-reports', { params: { year: year.value, somtop_id: person.value || undefined } }); filters.value = r.data.filters || { people: [] }; record.value = r.data.records?.find(item => String(item.id) === String(person.value)) || null } catch (e) { record.value = null; swalError('โหลดข้อมูลไม่สำเร็จ', e.response?.data?.message || 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้') } finally { loading.value = false } }
const exportWord = async () => { exporting.value = true; try { const r = await api.get('/performance-reports/export-word', { params: { year: year.value, somtop_id: person.value }, responseType: 'blob' }); const u = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = u; a.download = `ประเมินผลงาน_${year.value}.docx`; a.click(); URL.revokeObjectURL(u) } catch (e) { swalError('สร้างไฟล์ไม่สำเร็จ', e.response?.data?.message || 'ไม่สามารถสร้างไฟล์ Word ได้') } finally { exporting.value = false } }
watch([year, person], load); onMounted(load)
</script>
<style scoped>.performance-page{color:var(--color-text)}.filter-controls{display:flex;gap:20px}.filter-group{min-width:280px}.report-card{padding:0;overflow:hidden}.report-heading{display:flex;justify-content:space-between;padding:20px;border-bottom:1px solid var(--color-border)}.report-heading h2{margin:0}.data-table th{white-space:nowrap;background:#f8fafc}.empty-state{padding:48px;text-align:center;color:var(--color-text-muted)}@media(max-width:700px){.filter-controls{flex-direction:column}.filter-group{min-width:0}.page-header{gap:12px;flex-direction:column;align-items:stretch}}</style>
