<template>
  <div class="manage-layout performance-page">
    <div class="page-header"><div><h1 class="page-title">ประเมินผลงานรอบปี</h1><p class="page-subtitle">สรุปผลการปฏิบัติหน้าที่รายบุคคล</p></div><button class="btn-primary" :disabled="!person || exporting" @click="exportWord">📄 ดาวน์โหลด Word</button></div>
    <section class="card filter-card"><div class="filter-controls"><div class="filter-group"><label>รอบปีประเมิน</label><select v-model="year"><option v-for="y in years" :key="y" :value="y">{{ yearLabel(y) }}</option></select></div><div class="filter-group"><label>บุคคล</label><select v-model="person"><option value="">เลือกบุคคล</option><option v-for="p in filters.people" :key="p.id" :value="String(p.id)">{{ p.full_name }}{{ p.position_name ? ` (${p.position_name})` : '' }}</option></select></div></div></section>
    <section v-if="loading" class="card empty-state">กำลังโหลดข้อมูล...</section>
    <section v-else-if="!person" class="card empty-state">กรุณาเลือกรอบปีและบุคคลเพื่อแสดงข้อมูล</section>
    <section v-else-if="record" class="profile-report card">
      <div class="profile-hero"><div class="profile-avatar">{{ initials(record.full_name) }}</div><div class="profile-identity"><h2>{{ record.full_name }}</h2><p>{{ record.position_name || 'ผู้พิพากษาสมทบ' }} · {{ record.occupation || 'ไม่ระบุอาชีพ' }}</p><span>{{ yearLabel(year) }}</span></div></div>
      <div class="report-heading"><div><h2>สรุปผลการปฏิบัติหน้าที่</h2><p>ข้อมูลประกอบการประเมินผลการปฏิบัติหน้าที่</p></div></div>
      <div class="metric-grid"><div class="metric-card blue"><span>ปฏิบัติหน้าที่ตามเวร</span><strong>{{ record.duty_days }}</strong><small>วัน</small></div><div class="metric-card green"><span>หน้าที่อื่น / กิจกรรม</span><strong>{{ record.activity_count }}</strong><small>ครั้ง</small></div><div class="metric-card amber"><span>ผู้ขอเปลี่ยนเวร</span><strong>{{ record.swap_count }}</strong><small>ครั้ง</small></div></div>
      <div class="detail-section"><h3>ข้อมูลการลา</h3><div class="leave-summary">{{ leaveSummary(record) }}</div></div>
    </section>
  </div>
</template>
<script setup>
import { ref, computed, onMounted, watch } from 'vue'; import api from '../services/api'; import { swalError } from '../utils/swal'
const now = new Date(); const currentAnnualYear = now.getMonth() < 3 ? now.getFullYear() - 1 : now.getFullYear(); const year = ref(String(currentAnnualYear)); const person = ref(''); const filters = ref({ people: [] }); const record = ref(null); const loading = ref(false); const exporting = ref(false); const years = Array.from({ length: 15 }, (_, index) => currentAnnualYear - index)
const yearLabel = value => { const buddhist = Number(value) + 543; return `รอบปี ${buddhist} (1 เม.ย. ${String(buddhist).slice(-2)} - 31 มี.ค. ${String(buddhist + 1).slice(-2)})` }
const leaveSummary = row => { const leaves = row?.leaves || {}; const personal = ['ลากิจส่วนตัว', 'ลากิจ', 'ลาพักผ่อน'].reduce((sum, key) => sum + Number(leaves[key]?.days || 0), 0); return `ลากิจ/ลาพักผ่อน ${personal || '-'} วัน · ลาป่วย ${leaves['ลาป่วย']?.count || '-'} ครั้ง · ขาด - วัน (ไม่ลา)` }
const initials = name => String(name || '-').replace(/^(นาย|นางสาว|นาง|คุณ)/, '').trim().slice(0, 2)
const load = async () => { loading.value = true; try { const r = await api.get('/performance-reports', { params: { year: year.value, somtop_id: person.value || undefined } }); filters.value = r.data.filters || { people: [] }; record.value = r.data.records?.find(item => String(item.id) === String(person.value)) || null } catch (e) { record.value = null; swalError('โหลดข้อมูลไม่สำเร็จ', e.response?.data?.message || 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้') } finally { loading.value = false } }
const exportWord = async () => { exporting.value = true; try { const r = await api.get('/performance-reports/export-word', { params: { year: year.value, somtop_id: person.value }, responseType: 'blob' }); const u = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = u; a.download = `ประเมินผลงาน_${year.value}.docx`; a.click(); URL.revokeObjectURL(u) } catch (e) { swalError('สร้างไฟล์ไม่สำเร็จ', e.response?.data?.message || 'ไม่สามารถสร้างไฟล์ Word ได้') } finally { exporting.value = false } }
watch([year, person], load); onMounted(load)
</script>
<style scoped>.performance-page{color:var(--color-text)}.filter-controls{display:flex;gap:20px}.filter-group{min-width:280px}.profile-report{max-width:900px;margin:24px auto;padding:0;overflow:hidden}.profile-hero{display:flex;align-items:center;gap:18px;padding:28px;background:linear-gradient(135deg,#eff6ff,#f8fafc);border-bottom:1px solid #dbeafe}.profile-avatar{display:grid;place-items:center;width:72px;height:72px;border-radius:50%;background:#2563eb;color:white;font-size:24px;font-weight:800}.profile-identity h2{margin:0 0 6px;font-size:22px}.profile-identity p{margin:0 0 8px;color:#64748b}.profile-identity span{font-size:13px;color:#1d4ed8;font-weight:700}.report-heading{padding:22px 28px 10px}.report-heading h2{margin:0}.report-heading p{margin:6px 0;color:#64748b;font-size:13px}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:12px 28px 24px}.metric-card{display:grid;gap:5px;padding:18px;border:1px solid #e5e7eb;border-top:4px solid;border-radius:10px;background:#fff}.metric-card span,.metric-card small{color:#64748b;font-size:13px}.metric-card strong{font-size:30px;line-height:1.1}.metric-card.blue{border-top-color:#2563eb}.metric-card.blue strong{color:#1d4ed8}.metric-card.green{border-top-color:#16a34a}.metric-card.green strong{color:#15803d}.metric-card.amber{border-top-color:#d97706}.metric-card.amber strong{color:#b45309}.detail-section{margin:0 28px 28px;padding-top:20px;border-top:1px solid #e5e7eb}.detail-section h3{margin:0 0 12px;font-size:16px}.leave-summary{padding:14px 16px;border-radius:8px;background:#f8fafc;color:#374151;line-height:1.8}@media(max-width:700px){.filter-controls{flex-direction:column}.filter-group{min-width:0}.page-header{gap:12px;flex-direction:column;align-items:stretch}.profile-hero{align-items:flex-start}.metric-grid{grid-template-columns:1fr;padding:12px 20px 20px}.report-heading,.detail-section{margin-left:0;margin-right:0;padding-left:20px;padding-right:20px}}</style>
